created additional tests for edit unit functionality
ArtemPerehonchuk/rentzila-playwright-team pull request #1
Opened 2024-11-19 12:46 UTC by ArtemPerehonchuk

Created tests for edit unit. Test cases: C274, 275, 541, 276, 543

2024-11-20 13:58 UTC, DenysT07 requested changes

2024-11-20 13:58 UTC, DenysT07 commented on helpers/api.helper.ts
В репозиторії не має бути закоменченого коду

2024-11-20 13:58 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +        await this.page.waitForTimeout(2000);
Треба намагатись уникати пауз, спробуй бодати якийсь метод waitUntil

2024-11-20 13:58 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +        for(let i = 0; i < unitImageBlocks.length; i++) {
Використай тут For of, замість звичайного цикла

2024-11-20 13:58 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +        return await this.unitNameInput.inputValue();
Ящо є return, то await можна не писати

2024-11-20 13:58 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +            await this.editedUnitUploadFileInput.setInputFiles(path.resolve(`data/photo/${photoFileNames[photoFileNameIndex]}.jpg`));
Винести резолв шляху в хелпер, заміть того щоб рандомізувати індекс, використай фейкер, який буде повертати випадкове значення з масиву

2024-11-20 13:58 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +            if (uploadedImages === 1) {
ці if else можна замінити однією стрічкою - `await this.uploadPhotos(4 - uploadedImages)`

2024-11-20 13:58 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +            let uploadedImages = await this.getEditedUnitUploadedPhotosCount();
const

2024-11-20 13:58 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +            if (await this.uploadPhotoErrorPopUp.isVisible()) {
If else можна прибрати і замість нього просто поставити `waitUntilUploadPhotoErrorPopUp`  щоб воно фейлилось коли попапки немає

2024-11-20 13:58 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +        return await this.editedUnitImages.nth(numberOfImage - 1).getAttribute('src');
Ящо є return, то await можна не писати

2024-11-20 13:58 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +        const [fileChooser] = await Promise.all([
зроби без проміса

2024-11-20 13:58 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +        const photoFileNameIndex = Math.floor(Math.random() * 15)
використай фейкер

2024-11-20 13:58 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +    async fillMinOrderPriceInput(value: any) {
Чому тип any?

2024-11-20 13:58 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +        await this.page.waitForTimeout(2000);
використай waitUntil

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
Спробуй використати fixture замість ініціалізації сторінок в біфорі

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +test('Test case C274: Check image section functionality @edit', async({page}) => {
Тести мають бути незалежними, якщо тобі треба щось редагувати то треба спочатку в тесті це створити, або в хуках, не опираючись на результати попередніх тестів

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +    }catch(error) {
Try catch тут не потрібен

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +        if(await editUnitPage.successEditUnitMsg.isVisible()) {
Якщо не буде меседжа то це баг, але по твоєму коду я бачу що тест просто зупиниться і видасть що все успішно пройдено.

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +    const over100CharStr = faker.string.alpha({length: 101});
перенеси це в окремий метод в хелпер

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +    const inputValues = [
немає сенсу з цього масиву, генеруй дані тільки там де воні потрібні, якщо ти генеруєш дані в середині тесту

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +    for(const inputValue of inputValues) {
Зроби це просто окремими експектами, тут не потрібен ні for of ні switch case

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +    for(let i = paymentMethods.length - 1; i >= 0; i--) {
спробуй зробити for of над тестом, і по мінімуму використовувати індекси

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +    const random10Digits = (faker.number.int({ min: 1000000000, max: 9999999999 })).toString()
Використай `faker.string.numeric(10)`

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +        '<>{};^@!#$%?()|\/`~',
всі ці символи можна генерувати фейкером

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +    for (const value of inputValues) {
Зроби це просто окремими експектами, тут не потрібен ні for of ні switch case

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +        await expect(priceOptions).toContain(additionalPriceItems[i]);
так тут же ігнориться нульвий індекс в перевірці

2024-11-20 13:58 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +    if(randomAdditionalPriceDropDownOption.toLowerCase() === 'метр кв.') {
спробуй зробити for of над тестом. і не використовувати такі складні і не читабельні конструкції

2024-11-21 06:44 UTC, ArtemPerehonchuk commented on tests/test.edit.unit.spec.ts
Я перейшов на використання фікстур в наступній таскі. Тому після її мерджу проект буде з фікстурами.

2024-11-21 06:47 UTC, ArtemPerehonchuk commented on tests/test.edit.unit.spec.ts
> +test('Test case C274: Check image section functionality @edit', async({page}) => {
@edit це маркер який я додав щоб запускати не всі тести, а тільки помічені. Наприклад: npx playwright test tests/test.edit.unit.spec.ts --config=playwright.config.chrome.ts --workers=1 --grep @edit

2024-11-21 06:47 UTC, ArtemPerehonchuk commented on tests/test.edit.unit.spec.ts
> +    }catch(error) {
Добре

2024-11-21 06:48 UTC, ArtemPerehonchuk commented on tests/test.edit.unit.spec.ts
> +        if(await editUnitPage.successEditUnitMsg.isVisible()) {
Так там і є баг, який інколи з'являється

2024-11-21 06:51 UTC, ArtemPerehonchuk commented on tests/test.edit.unit.spec.ts
> +        await expect(priceOptions).toContain(additionalPriceItems[i]);
Так. Я не хотів брати дефолтне значення, тому ігнорував його

2024-11-22 11:19 UTC, ArtemPerehonchuk commented
Пофіксив

2024-11-25 15:21 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +test('Test case C274: Check image section functionality @edit', async({page}) => {
Ти можеш запустити тільки один тест C274 не запускаючи перед цим ніякі інші тести?

2024-11-25 15:26 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +        if(await editUnitPage.successEditUnitMsg.isVisible()) {
Так якщо баг існує, то чому тест його не показує? Якщо ти хочеш щоб цей баг не фейлив тобі тест і залишити так як зараз, то тоді треба залишити в цьому місці комент (TODO) з посиланням на тікев в якому заведений цей баг і поясненням.

2024-11-25 15:34 UTC, DenysT07 requested changes

2024-11-25 15:34 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +        const fileChooser = await fileChooserPromise;
Можна видалити змінну і повертати одразу значення

2024-11-26 07:53 UTC, ArtemPerehonchuk commented on tests/test.edit.unit.spec.ts
> +test('Test case C274: Check image section functionality @edit', async({page}) => {
Я прибрав маркер.

2024-11-26 07:54 UTC, ArtemPerehonchuk commented on tests/test.edit.unit.spec.ts
> +        if(await editUnitPage.successEditUnitMsg.isVisible()) {
Я можу це прибрати. Тому що цей баг також валить інші тести.

2024-11-28 11:57 UTC, DenysT07 requested changes

2024-11-28 11:57 UTC, DenysT07 commented on pages/edit.unit.page.ts
> +        const photoFileNameIndex = faker.number.int({ min: 0, max: 14 });
Використай ось цей метод https://fakerjs.dev/api/helpers.html#arrayelement

2024-11-28 11:57 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +    }else return
Так а навіщо if else?

2024-11-28 11:57 UTC, DenysT07 commented on tests/test.edit.unit.spec.ts
> +    const randomSpecialCharsSequence = faker.helpers.arrayElements(specialChars.split(''), { min: 3, max: 20 }).join('');
Заміни на https://fakerjs.dev/api/string.html#symbol

2024-11-28 12:53 UTC, ArtemPerehonchuk commented
Пофіксив

2024-12-02 12:36 UTC, DenysT07 approved these changes

2024-12-03 07:09 UTC, merged