favorite units task 1
ArtemPerehonchuk/rentzila-playwright-team pull request #3
Opened 2024-11-22 10:59 UTC by sharksystems

Changes: added fixtures.ts, added a command for running tests in ui mode, added API requests for managing favorite units
Added test cases C300, 302, 305, 311, 315, 744, 745 - Favorite units flow

2024-11-27 09:19 UTC, ArtemPerehonchuk requested changes

2024-11-27 09:19 UTC, ArtemPerehonchuk commented on pages/owner.units.page.ts
> +        await favBtn.click();
А чому просто не зробити клік по локатору в тесті?

2024-11-27 09:19 UTC, ArtemPerehonchuk commented on pages/owner.units.page.ts
> +    async verifyAllUnitsDisplayedWithCategory(expectedCategory: string) {
А чому не зробити перевірки в самому тесті? І try/catch мені здається тут не потрібен. Чи можна зробити щось накшталт:
const unitCardsCount = await ownerUnitsPage.getUnitCardsLength();
if (unitCardsCount === 0) {
                await expect(ownerUnitsPage.unitsEmptyTitle).toHaveText(`Оголошення в категорії "${expectedCategory}" не знайдені`);
                await expect(ownerUnitsPage.unitsEmptyMsg).toHaveText("Ви можете змінити пошуковий запит або скинути всі фільтри");
            }else {
        for (let i = 0; i < unitCardsCount; i++) {
            const category = await ownerUnitsPage.getCategoryOnUnit(i);
            await expect(category).toBe(expectedCategory);
        }

2024-11-27 09:19 UTC, ArtemPerehonchuk commented on pages/owner.units.page.ts
> +    async verifyFavoriteStatusOnUnit(title: string, status: 'active' | 'inactive') {
І ці перевірки я б також робив в самому тесті

2024-11-27 09:19 UTC, ArtemPerehonchuk commented on pages/owner.units.page.ts
> +        try {
try/catch тут не потрібен мені здається

2024-11-27 09:19 UTC, ArtemPerehonchuk commented on pages/products.page.ts
> +        await favBtn.click();
Чи можна зробити клік на кнопку в самому тесті:
await productsPage. favoriteBtn.click()

2024-11-27 09:19 UTC, ArtemPerehonchuk commented on pages/profile.page.ts
> +    favoriteUnitsTab = this.page.getByTestId('variant').filter({hasText: "Обрані оголошення"});
Я би не використовув тут статичний текст, або підібрав би якийсь інший локатор

2024-11-27 09:19 UTC, ArtemPerehonchuk commented on tests/test.favorite.unit.spec.ts
> +        // await expect(ownerUnitsPage.unitSearchInput).toHaveValue('');
Коментарі можна прибрати

2024-11-27 09:19 UTC, ArtemPerehonchuk commented on tests/test.favorite.unit.spec.ts
> +        let nonExistentName = 'тест1234567890'
Я б прикрутив якійсь фейкер

2024-11-27 09:19 UTC, ArtemPerehonchuk commented on tests/test.favorite.unit.spec.ts
> +
я б зробив щось накшталт:
await expect(ownerUnitsPage.unitsEmptyTitle).toHaveText('Оголошення за назвою "${nonExistentName}" не знайдені');
await expect(ownerUnitsPage.unitsEmptyMsg).toHaveText(Ви можете змінити пошуковий запит або скинути всі фільтри);

2024-11-27 09:19 UTC, ArtemPerehonchuk commented on tests/test.favorite.unit.spec.ts
> +        await homePage.loginUser(process.env.VALID_EMAIL || '', process.env.VALID_PASSWORD || '');
я б виніс логі та пароль. вконстанти на початку файлу

2024-11-27 09:19 UTC, ArtemPerehonchuk commented on tests/test.favorite.unit.spec.ts
> +        const category3 = "Складська техніка"
я б виніс назви в json

2024-12-01 15:36 UTC, sharksystems commented on tests/test.favorite.unit.spec.ts
> +        const category3 = "Складська техніка"
Все це діло вже переніс в наступному таску

2024-12-01 15:37 UTC, sharksystems commented on tests/test.favorite.unit.spec.ts
> +        await homePage.loginUser(process.env.VALID_EMAIL || '', process.env.VALID_PASSWORD || '');
Зробив, але в майбутньому бажано зробити це як глобальні змінні, щоб не прописувати в кожній тест спеці

2024-12-01 15:40 UTC, sharksystems commented on tests/test.favorite.unit.spec.ts
> +        // await expect(ownerUnitsPage.unitSearchInput).toHaveValue('');
Закоментив степи, які повинні бути в тесті, але заблочені. Якщо їх просто прибрати, то можуть бути інші питання)
В нашому випадку це фікситись не буде, але на мою думку подібні специфіки не повинні впливати на те як ми формуємо наш підхід до проекту.

2024-12-04 08:40 UTC, ArtemPerehonchuk approved these changes

2024-12-05 15:06 UTC, DenysT07 requested changes

2024-12-05 15:06 UTC, DenysT07 commented on fixtures.ts
> +        const productsPage = new ProductsPage(page);
змінна не потрібна тут

2024-12-05 15:06 UTC, DenysT07 commented on helpers/api.helper.ts
> +        if (adminAccessToken === null) {
напиши просто !adminAccessToken

2024-12-05 15:06 UTC, DenysT07 commented on helpers/api.helper.ts
> +            const response = await this.request.get(`https://dev.rentzila.com.ua/api/units/?page=${currentPage}`);
Всі URL можна перенести в окремий файл, як приклад - export const baseUrl = process.env.BASE_BACKEND_URL + process.env.SERVER_NODE;
import 'dotenv/config';

export const AdminEndpoints = {
    admin: () => `${baseUrl}/admin/`,
    login: () => `${AdminEndpoints.admin()}login`,
    adminUsers: () => `${AdminEndpoints.admin()}adminUsers/`,
    listWS: () => `${AdminEndpoints.adminUsers()}listWS`,
    wsUsers: () => `${AdminEndpoints.adminUsers()}WSUsers/`,
    wsUser: (username: string) => `${AdminEndpoints.adminUsers()}WSUsers/${username}/`,
    groupManagment: () => `${AdminEndpoints.admin()}groupManagement/`,
}

2024-12-05 15:06 UTC, DenysT07 commented on helpers/api.helper.ts
> +                if (error.message.includes('aborted') || error.message.includes('closed')) {
Почитай як ставити ексепшени в playwright запитах

2024-12-05 15:06 UTC, DenysT07 commented on pages/owner.units.page.ts
> +    getPaginationBtnWithIndex(index: number) {
гетери тут мають бути асинхронні

2024-12-05 15:06 UTC, DenysT07 commented on pages/owner.units.page.ts
> +    async enterUnitSearch(text: string, caseOption: 'uppercase' | 'lowercase' | 'paste' | 'default' = 'default') {
"'uppercase' | 'lowercase'" дані мають генеруватись в самому тесті
Функфія pased має бути реалізована для всіх елементів (на другому рівні пейджі або через хелпер якщо немає двохрівневої пейджі)

2024-12-05 15:06 UTC, DenysT07 commented on pages/products.page.ts
> +    async getTitleFromUnitCard (index: number) {
Прибери зайві змінні

2024-12-05 15:06 UTC, DenysT07 commented on tests/test.favorite.unit.spec.ts
> +        // await expect(ownerUnitsPage.unitSearchInput).toHaveValue('');
В коді не має бути закоменченого коду. Якщо воно не буде фікситись то і тут воно такаж не потрібно

2024-12-05 15:06 UTC, DenysT07 commented on tests/test.favorite.unit.spec.ts
> +        expect(ownerUnitsPage.unitsEmptyTitle).toHaveText(`Оголошення за назвою "${nonExistentName}" не знайдені`);
А де await?

2024-12-06 11:13 UTC, sharksystems commented on pages/owner.units.page.ts
> +    getPaginationBtnWithIndex(index: number) {
Не зовсім, тут гетер просто повертає значення локатора. Це не впливає на порядок виконання.
Методи які резолвлять цей локатор на сторінці по типу:
await ownerUnitsPage.getPaginationBtnWithIndex(1).click();
вже асинхронні, і якщо тут пропустити await, то виникнуть проблеми з таймінгом.

2024-12-06 11:24 UTC, sharksystems commented on helpers/api.helper.ts
> +                if (error.message.includes('aborted') || error.message.includes('closed')) {
Можеш будь ласка скинути якийсь ресурс по цій темі? Коли шукаю по запиту "playwright exception handling" в основному розказуть про той же try/catch.

Додам тут контекст по цьому методу: try/catch тут я додав тому що плейрайт кидає помилку і завершує тест якщо зв'язок з сервером закривається (на його думку, несподівано). Навіть після отримання і валідації відповіді. Я випробував декілька різних способів, але це єдиний який працював стабільно.
Якби я використовував keep-alive то цього всього не було б. Але саме з цим запитом якийсь баг, при якому запит безкінечно висить. З цього приводу теж дивився і пробував різні способи, і Connection: close це теж єдине з чим воно стабільно почало працювати.

2024-12-06 11:25 UTC, sharksystems commented on helpers/api.helper.ts
> +            const response = await this.request.get(`https://dev.rentzila.com.ua/api/units/?page=${currentPage}`);
Виправив це в наступному завданні, яке вже сюди замерджив.

2024-12-10 12:29 UTC, DenysT07 requested changes

2024-12-10 12:29 UTC, DenysT07 commented on pages/unit.page.ts
>      async checkUnitIsVisible(isExist: boolean = true) {
В чому суть цього метода? Навіщо IF Else всередині?

2024-12-10 13:25 UTC, sharksystems commented on pages/unit.page.ts
>      async checkUnitIsVisible(isExist: boolean = true) {
Не впевнений, цей метод використовується ще в самих перших тестах, в яких я не брав участі
![image](https://github.com/user-attachments/assets/d2d86c7e-e487-48b8-8d62-c8b7bf330f48)

2024-12-10 13:31 UTC, DenysT07 commented on pages/unit.page.ts
>      async checkUnitIsVisible(isExist: boolean = true) {
Спробуй розібратись в цьому методі і спростити його, як я бачу тут взагалі цей IF else не потрібен

2024-12-11 19:20 UTC, sharksystems commented on pages/unit.page.ts
>      async checkUnitIsVisible(isExist: boolean = true) {
Спростив. По суті робить те саме.

2024-12-13 11:55 UTC, DenysT07 approved these changes

2024-12-13 13:56 UTC, merged